version: "3.5"

services:
  # redis:
  #   image: redis:lastest
  #   # network_mode: "host"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.redis
  #   # ports:
  #   # - "6379:6379"
  #   volumes:
  #     - ./redis.conf:/etc/redis/redis.conf

  db:
    # image: mysql:5.7
    # volumes:
    #   - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    build: ./db_service
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: db
      # MYSQL_USER: db
      # MYSQL_PASSWORD: db

  sails-boilerplate-v1:
    links:
      - db
      # - redis

    image: sails-boilerplate-v1:lastest
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "1337:1337"
    restart: always
