name: Build & Deploy workflow
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
      name: Run tests

      # Linux VM
      runs-on: ubuntu-latest
      # Node.js Docker image for VM
      container:
        image: node:erbium
      # All steps for test
      steps:
        - name: Checkout branch to VM
          uses: actions/checkout@v1
        - name : Install dependences
          run: npm install
        - name: Run ESLint & Jest
          run: |
            npm run test
        - name: Unit test api, flow
          run: |
            npm run test-flow

  # build:
  #   # Job name is Greeting
  #   name: test
  #   # This job runs on Linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
  #     - name: Hello world
  #       uses: actions/hello-world-javascript-action@v1
  #       with:
  #         who-to-greet: 'Mona the Octocat'
  #       id: hello
  #     # This step prints an output (time) from the previous step's action.
  #     - name: Echo the greeting's time
  #       run: echo 'The time was ${{ steps.hello.outputs.time }}.'